export const TEST_ACTION = 'TEST_ACTION';
// Screen Actions
export const GET_SCREEN_INIT = 'GET_SCREEN_INIT';
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const CHANGE_STATUS_ASYNC = 'CHANGE_STATUS_ASYNC';
export const START_IDLE_TIMING = 'START_IDLE_TIMING';
export const GO_IDLE = 'GO_IDLE';
export const RESET_SUBMIT_TIME = 'RESET_SUBMIT_TIME';
export const PROCESS_INPUT_ASYNC = 'PROCESS_INPUT_ASYNC';
export const CHANGE_LOCK = 'CHANGE_LOCK';
export const UNLOCK_SUCCESS = 'UNLOCK_SUCCESS';
export const UNLOCK_FAIL = 'UNLOCK_FAIL';
export const LOCK_SUCCESS = 'LOCK_SUCCESS';
export const LOCK_FAIL = 'LOCK_FAIL';
export const START_LOCK_ASYNC = 'START_LOCK_ASYNC';